`((host . "jfc.im")
  (port . 6667)
  (ssl . #f)
  (modules . ((core irc)
	      (commands init)
	      (commands modules)
	      (commands reload)
	      (commands channels)
	      (commands nick))))
